"""Create Phase 2 database schema

Revision ID: 4ad1df852a49
Revises:
Create Date: 2026-08-12 12:56:30.281686

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4ad1df852a49"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum("admin", name="role", create_constraint=True),
            server_default="admin",
            nullable=False,
        ),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("role", name=op.f("uq_users_role")),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)

    op.create_table(
        "exams",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("admin_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("course_code", sa.String(length=50), nullable=False),
        sa.Column("course_title", sa.String(length=255), nullable=False),
        sa.Column("instructions", sa.Text(), nullable=True),
        sa.Column("time_limit_minutes", sa.Integer(), nullable=False),
        sa.Column(
            "monitor_type",
            sa.Enum("face", "eye_gaze", name="monitor_type", create_constraint=True),
            nullable=False,
        ),
        sa.Column(
            "release_option",
            sa.Enum(
                "immediate", "scheduled", name="release_option", create_constraint=True
            ),
            server_default="immediate",
            nullable=False,
        ),
        sa.Column("scheduled_release_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("exam_link_token", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "release_option <> 'scheduled' OR scheduled_release_at IS NOT NULL",
            name=op.f("ck_exams_scheduled_release_has_time"),
        ),
        sa.CheckConstraint(
            "time_limit_minutes > 0", name=op.f("ck_exams_positive_time_limit")
        ),
        sa.ForeignKeyConstraint(
            ["admin_id"],
            ["users.id"],
            name=op.f("fk_exams_admin_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exams")),
    )
    with op.batch_alter_table("exams", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_exams_admin_id"), ["admin_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_exams_course_code"), ["course_code"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_exams_exam_link_token"), ["exam_link_token"], unique=True
        )

    op.create_table(
        "password_reset_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "attempts >= 0 AND attempts <= 5",
            name=op.f("ck_password_reset_tokens_attempt_range"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_password_reset_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_password_reset_tokens")),
    )
    with op.batch_alter_table("password_reset_tokens", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_password_reset_tokens_expires_at"),
            ["expires_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_password_reset_tokens_token_hash"),
            ["token_hash"],
            unique=True,
        )
        batch_op.create_index(
            batch_op.f("ix_password_reset_tokens_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "questions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("exam_id", sa.Integer(), nullable=False),
        sa.Column("question_text", sa.Text(), nullable=False),
        sa.Column(
            "question_type",
            sa.Enum(
                "mcq",
                "open_ended",
                "short_answer",
                name="question_type",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("marks", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column("options", sa.JSON(), nullable=True),
        sa.Column("correct_answer", sa.Text(), nullable=True),
        sa.Column(
            "short_answer_case_sensitive",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "short_answer_trim_whitespace",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("marks > 0", name=op.f("ck_questions_positive_marks")),
        sa.CheckConstraint("position > 0", name=op.f("ck_questions_positive_position")),
        sa.ForeignKeyConstraint(
            ["exam_id"],
            ["exams.id"],
            name=op.f("fk_questions_exam_id_exams"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_questions")),
        sa.UniqueConstraint("exam_id", "position", name="question_position"),
    )
    with op.batch_alter_table("questions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_questions_exam_id"), ["exam_id"], unique=False
        )

    op.create_table(
        "submissions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("exam_id", sa.Integer(), nullable=False),
        sa.Column("candidate_name", sa.String(length=255), nullable=False),
        sa.Column("candidate_email", sa.String(length=255), nullable=False),
        sa.Column("responses", sa.JSON(), nullable=False),
        sa.Column("resume_token_hash", sa.String(length=64), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_saved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("submission_reason", sa.String(length=50), nullable=True),
        sa.Column("warn_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "submitted_at IS NULL OR submitted_at >= started_at",
            name=op.f("ck_submissions_submission_after_start"),
        ),
        sa.CheckConstraint(
            "warn_count >= 0 AND warn_count <= 3",
            name=op.f("ck_submissions_warning_range"),
        ),
        sa.ForeignKeyConstraint(
            ["exam_id"],
            ["exams.id"],
            name=op.f("fk_submissions_exam_id_exams"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_submissions")),
        sa.UniqueConstraint("exam_id", "candidate_email", name="candidate_exam"),
    )
    with op.batch_alter_table("submissions", schema=None) as batch_op:
        batch_op.create_index(
            "ix_submissions_candidate_email", ["candidate_email"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_submissions_exam_id"), ["exam_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_submissions_resume_token_hash"),
            ["resume_token_hash"],
            unique=True,
        )
        batch_op.create_index(
            batch_op.f("ix_submissions_started_at"), ["started_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_submissions_submitted_at"), ["submitted_at"], unique=False
        )

    op.create_table(
        "verification_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("exam_id", sa.Integer(), nullable=False),
        sa.Column("candidate_name", sa.String(length=255), nullable=False),
        sa.Column("candidate_email", sa.String(length=255), nullable=False),
        sa.Column("otp_hash", sa.String(length=64), nullable=False),
        sa.Column("magic_token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "attempts >= 0 AND attempts <= 5",
            name=op.f("ck_verification_tokens_attempt_range"),
        ),
        sa.ForeignKeyConstraint(
            ["exam_id"],
            ["exams.id"],
            name=op.f("fk_verification_tokens_exam_id_exams"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_verification_tokens")),
    )
    with op.batch_alter_table("verification_tokens", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_verification_tokens_candidate_email"),
            ["candidate_email"],
            unique=False,
        )
        batch_op.create_index(
            "ix_verification_tokens_exam_email",
            ["exam_id", "candidate_email"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_verification_tokens_expires_at"),
            ["expires_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_verification_tokens_magic_token_hash"),
            ["magic_token_hash"],
            unique=True,
        )
        batch_op.create_index(
            batch_op.f("ix_verification_tokens_otp_hash"), ["otp_hash"], unique=False
        )

    op.create_table(
        "answer_grades",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("submission_id", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("awarded_marks", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column(
            "graded_by",
            sa.Enum("automatic", "admin", name="graded_by", create_constraint=True),
            nullable=True,
        ),
        sa.Column("grader_user_id", sa.Integer(), nullable=True),
        sa.Column("feedback", sa.Text(), nullable=True),
        sa.Column("graded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "awarded_marks IS NULL OR awarded_marks >= 0",
            name=op.f("ck_answer_grades_nonnegative_awarded_marks"),
        ),
        sa.ForeignKeyConstraint(
            ["grader_user_id"],
            ["users.id"],
            name=op.f("fk_answer_grades_grader_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
            name=op.f("fk_answer_grades_question_id_questions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["submissions.id"],
            name=op.f("fk_answer_grades_submission_id_submissions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_answer_grades")),
        sa.UniqueConstraint("submission_id", "question_id", name="submission_question"),
    )
    with op.batch_alter_table("answer_grades", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_answer_grades_grader_user_id"),
            ["grader_user_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_answer_grades_question_id"), ["question_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_answer_grades_submission_id"),
            ["submission_id"],
            unique=False,
        )

    op.create_table(
        "results",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("submission_id", sa.Integer(), nullable=False),
        sa.Column(
            "marks_obtained",
            sa.Numeric(precision=10, scale=2),
            server_default="0.00",
            nullable=False,
        ),
        sa.Column("total_marks", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "percentage",
            sa.Numeric(precision=5, scale=2),
            server_default="0.00",
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending_manual_review",
                "complete",
                name="result_status",
                create_constraint=True,
            ),
            server_default="pending_manual_review",
            nullable=False,
        ),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "marks_obtained >= 0", name=op.f("ck_results_nonnegative_marks_obtained")
        ),
        sa.CheckConstraint(
            "percentage >= 0 AND percentage <= 100",
            name=op.f("ck_results_percentage_range"),
        ),
        sa.CheckConstraint(
            "total_marks >= 0", name=op.f("ck_results_nonnegative_total_marks")
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["submissions.id"],
            name=op.f("fk_results_submission_id_submissions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_results")),
    )
    with op.batch_alter_table("results", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_results_released_at"), ["released_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_results_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_results_submission_id"), ["submission_id"], unique=True
        )

    op.create_table(
        "warning_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("submission_id", sa.Integer(), nullable=False),
        sa.Column(
            "violation_type",
            sa.Enum(
                "copy_paste",
                "screenshot_attempt",
                "focus_loss",
                "face_not_detected",
                "gaze_deviation",
                name="violation_type",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["submissions.id"],
            name=op.f("fk_warning_logs_submission_id_submissions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_warning_logs")),
    )
    with op.batch_alter_table("warning_logs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_warning_logs_occurred_at"), ["occurred_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_warning_logs_submission_id"), ["submission_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_warning_logs_violation_type"),
            ["violation_type"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("warning_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_warning_logs_violation_type"))
        batch_op.drop_index(batch_op.f("ix_warning_logs_submission_id"))
        batch_op.drop_index(batch_op.f("ix_warning_logs_occurred_at"))

    op.drop_table("warning_logs")
    with op.batch_alter_table("results", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_results_submission_id"))
        batch_op.drop_index(batch_op.f("ix_results_status"))
        batch_op.drop_index(batch_op.f("ix_results_released_at"))

    op.drop_table("results")
    with op.batch_alter_table("answer_grades", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_answer_grades_submission_id"))
        batch_op.drop_index(batch_op.f("ix_answer_grades_question_id"))
        batch_op.drop_index(batch_op.f("ix_answer_grades_grader_user_id"))

    op.drop_table("answer_grades")
    with op.batch_alter_table("verification_tokens", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_verification_tokens_otp_hash"))
        batch_op.drop_index(batch_op.f("ix_verification_tokens_magic_token_hash"))
        batch_op.drop_index(batch_op.f("ix_verification_tokens_expires_at"))
        batch_op.drop_index("ix_verification_tokens_exam_email")
        batch_op.drop_index(batch_op.f("ix_verification_tokens_candidate_email"))

    op.drop_table("verification_tokens")
    with op.batch_alter_table("submissions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_submissions_submitted_at"))
        batch_op.drop_index(batch_op.f("ix_submissions_started_at"))
        batch_op.drop_index(batch_op.f("ix_submissions_resume_token_hash"))
        batch_op.drop_index(batch_op.f("ix_submissions_exam_id"))
        batch_op.drop_index("ix_submissions_candidate_email")

    op.drop_table("submissions")
    with op.batch_alter_table("questions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_questions_exam_id"))

    op.drop_table("questions")
    with op.batch_alter_table("password_reset_tokens", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_password_reset_tokens_user_id"))
        batch_op.drop_index(batch_op.f("ix_password_reset_tokens_token_hash"))
        batch_op.drop_index(batch_op.f("ix_password_reset_tokens_expires_at"))

    op.drop_table("password_reset_tokens")
    with op.batch_alter_table("exams", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_exams_exam_link_token"))
        batch_op.drop_index(batch_op.f("ix_exams_course_code"))
        batch_op.drop_index(batch_op.f("ix_exams_admin_id"))

    op.drop_table("exams")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    # ### end Alembic commands ###
