"""add academic assessment and coursework phases

Revision ID: 9f2b52a8e49d
Revises: d93c5e7a12f4
Create Date: 2026-09-23 10:57:11.200702

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9f2b52a8e49d"
down_revision = "d93c5e7a12f4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "academic_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column(
            "is_current", sa.Boolean(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_academic_sessions")),
    )
    with op.batch_alter_table("academic_sessions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_academic_sessions_is_current"), ["is_current"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_academic_sessions_name"), ["name"], unique=True
        )

    op.create_table(
        "faculties",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=30), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_faculties")),
        sa.UniqueConstraint("name", name=op.f("uq_faculties_name")),
    )
    with op.batch_alter_table("faculties", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_faculties_code"), ["code"], unique=True)

    op.create_table(
        "departments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("faculty_id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=30), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["faculty_id"],
            ["faculties.id"],
            name=op.f("fk_departments_faculty_id_faculties"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_departments")),
        sa.UniqueConstraint("name", name=op.f("uq_departments_name")),
    )
    with op.batch_alter_table("departments", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_departments_code"), ["code"], unique=True)
        batch_op.create_index(
            batch_op.f("ix_departments_faculty_id"), ["faculty_id"], unique=False
        )

    op.create_table(
        "semesters",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("academic_session_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column(
            "is_current", sa.Boolean(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["academic_session_id"],
            ["academic_sessions.id"],
            name=op.f("fk_semesters_academic_session_id_academic_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_semesters")),
        sa.UniqueConstraint("academic_session_id", "name", name="session_semester"),
    )
    with op.batch_alter_table("semesters", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_semesters_academic_session_id"),
            ["academic_session_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_semesters_is_current"), ["is_current"], unique=False
        )

    op.create_table(
        "programmes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("department_id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=30), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("award", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
            name=op.f("fk_programmes_department_id_departments"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_programmes")),
        sa.UniqueConstraint("name", name=op.f("uq_programmes_name")),
    )
    with op.batch_alter_table("programmes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_programmes_code"), ["code"], unique=True)
        batch_op.create_index(
            batch_op.f("ix_programmes_department_id"), ["department_id"], unique=False
        )

    op.create_table(
        "assignments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("instructions", sa.Text(), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("max_marks", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column(
            "is_published", sa.Boolean(), server_default=sa.text("1"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_assignments_course_id_courses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_assignments_created_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assignments")),
    )
    with op.batch_alter_table("assignments", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_assignments_course_id"), ["course_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_assignments_created_by_id"), ["created_by_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_assignments_due_at"), ["due_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_assignments_is_published"), ["is_published"], unique=False
        )

    op.create_table(
        "course_announcements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "is_pinned", sa.Boolean(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
            name=op.f("fk_course_announcements_author_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_course_announcements_course_id_courses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_course_announcements")),
    )
    with op.batch_alter_table("course_announcements", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_course_announcements_author_id"), ["author_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_course_announcements_course_id"), ["course_id"], unique=False
        )

    op.create_table(
        "course_materials",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("uploaded_by_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("external_url", sa.String(length=2048), nullable=True),
        sa.Column("storage_name", sa.String(length=255), nullable=True),
        sa.Column("original_filename", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_course_materials_course_id_courses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by_id"],
            ["users.id"],
            name=op.f("fk_course_materials_uploaded_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_course_materials")),
        sa.UniqueConstraint(
            "storage_name", name=op.f("uq_course_materials_storage_name")
        ),
    )
    with op.batch_alter_table("course_materials", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_course_materials_course_id"), ["course_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_course_materials_uploaded_by_id"),
            ["uploaded_by_id"],
            unique=False,
        )

    op.create_table(
        "question_bank_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("lecturer_id", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column(
            "difficulty",
            sa.Enum(
                "easy",
                "medium",
                "hard",
                name="difficulty_level",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("question_text", sa.Text(), nullable=False),
        sa.Column(
            "question_type",
            sa.Enum(
                "mcq",
                "open_ended",
                "short_answer",
                name="bank_question_type",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("marks", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column("options", sa.JSON(), nullable=True),
        sa.Column("correct_answer", sa.Text(), nullable=True),
        sa.Column(
            "short_answer_case_sensitive",
            sa.Boolean(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "short_answer_trim_whitespace",
            sa.Boolean(),
            server_default=sa.text("1"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_question_bank_items_course_id_courses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["lecturer_id"],
            ["users.id"],
            name=op.f("fk_question_bank_items_lecturer_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_question_bank_items")),
    )
    with op.batch_alter_table("question_bank_items", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_question_bank_items_category"), ["category"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_question_bank_items_course_id"), ["course_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_question_bank_items_difficulty"),
            ["difficulty"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_question_bank_items_lecturer_id"),
            ["lecturer_id"],
            unique=False,
        )

    op.create_table(
        "assignment_submissions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("assignment_id", sa.Integer(), nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("text_response", sa.Text(), nullable=True),
        sa.Column("storage_name", sa.String(length=255), nullable=True),
        sa.Column("original_filename", sa.String(length=255), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("awarded_marks", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("feedback", sa.Text(), nullable=True),
        sa.Column("graded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("graded_by_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assignment_id"],
            ["assignments.id"],
            name=op.f("fk_assignment_submissions_assignment_id_assignments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["graded_by_id"],
            ["users.id"],
            name=op.f("fk_assignment_submissions_graded_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["users.id"],
            name=op.f("fk_assignment_submissions_student_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assignment_submissions")),
        sa.UniqueConstraint("assignment_id", "student_id", name="assignment_student"),
        sa.UniqueConstraint(
            "storage_name", name=op.f("uq_assignment_submissions_storage_name")
        ),
    )
    with op.batch_alter_table("assignment_submissions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_assignment_submissions_assignment_id"),
            ["assignment_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_assignment_submissions_graded_by_id"),
            ["graded_by_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_assignment_submissions_student_id"),
            ["student_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_assignment_submissions_submitted_at"),
            ["submitted_at"],
            unique=False,
        )

    op.create_table(
        "exam_accommodations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("exam_id", sa.Integer(), nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column(
            "extra_time_minutes", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "extra_time_minutes >= 0",
            name=op.f("ck_exam_accommodations_nonnegative_extra_time"),
        ),
        sa.ForeignKeyConstraint(
            ["exam_id"],
            ["exams.id"],
            name=op.f("fk_exam_accommodations_exam_id_exams"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["users.id"],
            name=op.f("fk_exam_accommodations_student_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exam_accommodations")),
        sa.UniqueConstraint("exam_id", "student_id", name="exam_student_accommodation"),
    )
    with op.batch_alter_table("exam_accommodations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_exam_accommodations_exam_id"), ["exam_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_exam_accommodations_student_id"),
            ["student_id"],
            unique=False,
        )

    with op.batch_alter_table("courses", schema=None) as batch_op:
        batch_op.add_column(sa.Column("semester_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("department_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("programme_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("level", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("credit_units", sa.Integer(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_courses_department_id"), ["department_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_courses_programme_id"), ["programme_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_courses_semester_id"), ["semester_id"], unique=False
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_courses_programme_id_programmes"),
            "programmes",
            ["programme_id"],
            ["id"],
            ondelete="SET NULL",
        )
        batch_op.create_check_constraint(
            "positive_course_level", "level IS NULL OR level > 0"
        )
        batch_op.create_check_constraint(
            "positive_credit_units", "credit_units IS NULL OR credit_units > 0"
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_courses_semester_id_semesters"),
            "semesters",
            ["semester_id"],
            ["id"],
            ondelete="SET NULL",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_courses_department_id_departments"),
            "departments",
            ["department_id"],
            ["id"],
            ondelete="SET NULL",
        )

    with op.batch_alter_table("exams", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("opens_at", sa.DateTime(timezone=True), nullable=True)
        )
        batch_op.add_column(
            sa.Column("closes_at", sa.DateTime(timezone=True), nullable=True)
        )
        batch_op.add_column(
            sa.Column("attempt_limit", sa.Integer(), server_default="1", nullable=False)
        )
        batch_op.add_column(
            sa.Column(
                "shuffle_questions",
                sa.Boolean(),
                server_default=sa.text("0"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "shuffle_options",
                sa.Boolean(),
                server_default=sa.text("0"),
                nullable=False,
            )
        )
        batch_op.create_index(
            batch_op.f("ix_exams_closes_at"), ["closes_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_exams_opens_at"), ["opens_at"], unique=False
        )
        batch_op.create_check_constraint("positive_attempt_limit", "attempt_limit > 0")
        batch_op.create_check_constraint(
            "exam_window_order",
            "closes_at IS NULL OR opens_at IS NULL OR closes_at > opens_at",
        )

    with op.batch_alter_table("questions", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("source_bank_item_id", sa.Integer(), nullable=True)
        )
        batch_op.create_index(
            batch_op.f("ix_questions_source_bank_item_id"),
            ["source_bank_item_id"],
            unique=False,
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_questions_source_bank_item_id_question_bank_items"),
            "question_bank_items",
            ["source_bank_item_id"],
            ["id"],
            ondelete="SET NULL",
        )

    with op.batch_alter_table("submissions", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "attempt_number", sa.Integer(), server_default="1", nullable=False
            )
        )
        batch_op.add_column(sa.Column("question_order", sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column("option_orders", sa.JSON(), nullable=True))
        batch_op.drop_constraint(batch_op.f("candidate_exam"), type_="unique")
        batch_op.create_unique_constraint(
            "candidate_exam_attempt", ["exam_id", "candidate_email", "attempt_number"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("submissions", schema=None) as batch_op:
        batch_op.drop_constraint("candidate_exam_attempt", type_="unique")
        batch_op.create_unique_constraint(
            batch_op.f("candidate_exam"), ["exam_id", "candidate_email"]
        )
        batch_op.drop_column("option_orders")
        batch_op.drop_column("question_order")
        batch_op.drop_column("attempt_number")

    with op.batch_alter_table("questions", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_questions_source_bank_item_id_question_bank_items"),
            type_="foreignkey",
        )
        batch_op.drop_index(batch_op.f("ix_questions_source_bank_item_id"))
        batch_op.drop_column("source_bank_item_id")

    with op.batch_alter_table("exams", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("ck_exams_exam_window_order"), type_="check"
        )
        batch_op.drop_constraint(
            batch_op.f("ck_exams_positive_attempt_limit"), type_="check"
        )
        batch_op.drop_index(batch_op.f("ix_exams_opens_at"))
        batch_op.drop_index(batch_op.f("ix_exams_closes_at"))
        batch_op.drop_column("shuffle_options")
        batch_op.drop_column("shuffle_questions")
        batch_op.drop_column("attempt_limit")
        batch_op.drop_column("closes_at")
        batch_op.drop_column("opens_at")

    with op.batch_alter_table("courses", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("ck_courses_positive_credit_units"), type_="check"
        )
        batch_op.drop_constraint(
            batch_op.f("ck_courses_positive_course_level"), type_="check"
        )
        batch_op.drop_constraint(
            batch_op.f("fk_courses_department_id_departments"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            batch_op.f("fk_courses_semester_id_semesters"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            batch_op.f("fk_courses_programme_id_programmes"), type_="foreignkey"
        )
        batch_op.drop_index(batch_op.f("ix_courses_semester_id"))
        batch_op.drop_index(batch_op.f("ix_courses_programme_id"))
        batch_op.drop_index(batch_op.f("ix_courses_department_id"))
        batch_op.drop_column("credit_units")
        batch_op.drop_column("level")
        batch_op.drop_column("programme_id")
        batch_op.drop_column("department_id")
        batch_op.drop_column("semester_id")

    with op.batch_alter_table("exam_accommodations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_exam_accommodations_student_id"))
        batch_op.drop_index(batch_op.f("ix_exam_accommodations_exam_id"))

    op.drop_table("exam_accommodations")
    with op.batch_alter_table("assignment_submissions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_assignment_submissions_submitted_at"))
        batch_op.drop_index(batch_op.f("ix_assignment_submissions_student_id"))
        batch_op.drop_index(batch_op.f("ix_assignment_submissions_graded_by_id"))
        batch_op.drop_index(batch_op.f("ix_assignment_submissions_assignment_id"))

    op.drop_table("assignment_submissions")
    with op.batch_alter_table("question_bank_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_question_bank_items_lecturer_id"))
        batch_op.drop_index(batch_op.f("ix_question_bank_items_difficulty"))
        batch_op.drop_index(batch_op.f("ix_question_bank_items_course_id"))
        batch_op.drop_index(batch_op.f("ix_question_bank_items_category"))

    op.drop_table("question_bank_items")
    with op.batch_alter_table("course_materials", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_course_materials_uploaded_by_id"))
        batch_op.drop_index(batch_op.f("ix_course_materials_course_id"))

    op.drop_table("course_materials")
    with op.batch_alter_table("course_announcements", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_course_announcements_course_id"))
        batch_op.drop_index(batch_op.f("ix_course_announcements_author_id"))

    op.drop_table("course_announcements")
    with op.batch_alter_table("assignments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_assignments_is_published"))
        batch_op.drop_index(batch_op.f("ix_assignments_due_at"))
        batch_op.drop_index(batch_op.f("ix_assignments_created_by_id"))
        batch_op.drop_index(batch_op.f("ix_assignments_course_id"))

    op.drop_table("assignments")
    with op.batch_alter_table("programmes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_programmes_department_id"))
        batch_op.drop_index(batch_op.f("ix_programmes_code"))

    op.drop_table("programmes")
    with op.batch_alter_table("semesters", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_semesters_is_current"))
        batch_op.drop_index(batch_op.f("ix_semesters_academic_session_id"))

    op.drop_table("semesters")
    with op.batch_alter_table("departments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_departments_faculty_id"))
        batch_op.drop_index(batch_op.f("ix_departments_code"))

    op.drop_table("departments")
    with op.batch_alter_table("faculties", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_faculties_code"))

    op.drop_table("faculties")
    with op.batch_alter_table("academic_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_academic_sessions_name"))
        batch_op.drop_index(batch_op.f("ix_academic_sessions_is_current"))

    op.drop_table("academic_sessions")
    # ### end Alembic commands ###
